// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	models "acortlink/core/domain/models"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ShortenApp is an autogenerated mock type for the ShortenApp type
type ShortenApp struct {
	mock.Mock
}

// CreateShortURL provides a mock function with given fields: ctx, url
func (_m *ShortenApp) CreateShortURL(ctx context.Context, url models.URLCreate) (string, error) {
	ret := _m.Called(ctx, url)

	if len(ret) == 0 {
		panic("no return value specified for CreateShortURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.URLCreate) (string, error)); ok {
		return rf(ctx, url)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.URLCreate) string); ok {
		r0 = rf(ctx, url)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.URLCreate) error); ok {
		r1 = rf(ctx, url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchUrl provides a mock function with given fields: ctx, path
func (_m *ShortenApp) SearchUrl(ctx context.Context, path string) (string, error) {
	ret := _m.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for SearchUrl")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, path)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, path)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewShortenApp creates a new instance of ShortenApp. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewShortenApp(t interface {
	mock.TestingT
	Cleanup(func())
}) *ShortenApp {
	mock := &ShortenApp{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
