// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// ShortenRepoRedis is an autogenerated mock type for the ShortenRepoRedis type
type ShortenRepoRedis struct {
	mock.Mock
}

// Save provides a mock function with given fields: ctx, key, value, _a3
func (_m *ShortenRepoRedis) Save(ctx context.Context, key string, value interface{}, _a3 time.Duration) error {
	ret := _m.Called(ctx, key, value, _a3)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}, time.Duration) error); ok {
		r0 = rf(ctx, key, value, _a3)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SearchUrl provides a mock function with given fields: ctx, path
func (_m *ShortenRepoRedis) SearchUrl(ctx context.Context, path string) (string, error) {
	ret := _m.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for SearchUrl")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, path)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, path)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewShortenRepoRedis creates a new instance of ShortenRepoRedis. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewShortenRepoRedis(t interface {
	mock.TestingT
	Cleanup(func())
}) *ShortenRepoRedis {
	mock := &ShortenRepoRedis{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
